baymax/admin/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import HiddenField, SubmitField, RadioField, DateField
from wtforms.validators import AnyOf

from ..user import USER_ROLE, USER_STATUS


class UserForm(Form):
    next = HiddenField()
    role_code = RadioField(u"Role", [AnyOf([str(val) for val in USER_ROLE.keys()])],
            choices=[(str(val), label) for val, label in USER_ROLE.items()])
    status_code = RadioField(u"Status", [AnyOf([str(val) for val in USER_STATUS.keys()])],
            choices=[(str(val), label) for val, label in USER_STATUS.items()])
    # A demo of datepicker.
    created_time = DateField(u'Created time')
    submit = SubmitField(u'Save')

baymax/__init__.py
# -*- coding: utf-8 -*-

from app import create_app

baymax/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

baymax/admin/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash
from flask.ext.login import login_required

from ..extensions import db
from ..decorators import admin_required

from ..user import User
from .forms import UserForm


admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/')
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template('admin/index.html', users=users, active='index')


@admin.route('/users')
@login_required
@admin_required
def users():
    users = User.query.all()
    return render_template('admin/users.html', users=users, active='users')


@admin.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()

        flash('User updated.', 'success')

    return render_template('admin/user.html', user=user, form=form)

baymax/api/__init__.py
# -*- coding: utf-8 -*-

from .views import api

baymax/api/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify
from flask.ext.login import current_user, login_required
from ..user import User
from ..monitor import MonitorValue


api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/<monitor_type>', methods=['GET'])
@login_required
def calories_out(monitor_type):
    res = []
    user_id = current_user.id
    mv = MonitorValue.query.filter_by(user_id=user_id, datatype=monitor_type).order_by('recode_date desc').limit(7).all()
    if not mv:
        return jsonify(result=[])
    for one_mv in mv[::-1]:
        res.append([one_mv.recode_date.strftime('%Y-%m-%d'), one_mv.value])
    return jsonify(result=res)

@api.route('/user/<username>/<monitor_type>', methods=['GET'])
def api_data(username, monitor_type):
    res = []
    user = User.query.filter_by(name=username).first()
    user_id = user.id
    mv = MonitorValue.query.filter_by(user_id=user_id, datatype=monitor_type).order_by('recode_date desc').limit(7).all()
    if not mv:
        return jsonify(result=[])
    for one_mv in mv[::-1]:
        res.append([one_mv.recode_date.strftime('%Y-%m-%d'), one_mv.value])
    return jsonify(result=res)

baymax/app.py
# -*- coding: utf-8 -*-

import os

from flask import Flask, request, render_template
from flask.ext.babel import Babel

from .config import DefaultConfig
from .user import User
from .frontend import frontend
from .monitor import monitor
from .api import api
from .admin import admin
from .extensions import db, mail, cache, login_manager, oid, celery
from .utils import INSTANCE_FOLDER_PATH


# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    api,
    admin,
    monitor
)


def create_app(config=None, app_name=None, blueprints=None):
    """Create a Flask app."""

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_path=INSTANCE_FOLDER_PATH, instance_relative_config=True)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app


def configure_app(app, config=None):
    """Different ways of configurations."""

    # http://flask.pocoo.org/docs/api/#configuration
    app.config.from_object(DefaultConfig)

    # http://flask.pocoo.org/docs/config/#instance-folders
    # app.config.from_pyfile('production.cfg', silent=True)

    # if config:
    #     app.config.from_object(config)

    # Use instance folder instead of env variables to make deployment easier.
    #app.config.from_envvar('%s_APP_CONFIG' % DefaultConfig.PROJECT.upper(), silent=True)


def configure_extensions(app):
    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    # cache.init_app(app)

    # flask-babel
    # babel = Babel(app)

    # @babel.localeselector
    # def get_locale():
    #     accept_languages = app.config.get('ACCEPT_LANGUAGES')
    #     return request.accept_languages.best_match(accept_languages)

    # flask-login
    login_manager.login_view = 'frontend.login'
    login_manager.refresh_view = 'frontend.reauth'
    login_manager.login_message = u""

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    login_manager.init_app(app)

    # @login_manager.unauthorized_handler
    # def unauthorized():
    #     # do stuff
    #     return a_response

    # flask-openid
    oid.init_app(app)

    #flask-rq
    # rqq.init_app(app)
    celery.init_app(app)


def configure_blueprints(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler(app.config['MAIL_SERVER'],
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/forbidden_page.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/page_not_found.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/server_error.html"), 500

baymax/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

baymax/frontend/views.py
# -*- coding: utf-8 -*-
from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort, jsonify)
from flask.ext.login import login_required, login_user, current_user, logout_user
from ..user import User
from ..monitor import Tokens
from ..extensions import db
from ..monitor import github_task_func, fitbit_task_func
import requests
import json
import base64


frontend = Blueprint('frontend', __name__)

@frontend.route('/<username>/show', methods=['GET'])
def user_show(username):
    user = User.query.filter_by(name=username).first()
    avatar = user.avatar
    return render_template('frontend/show.html', active='show', avatar=avatar, username=username)


@frontend.route('/show', methods=['GET', 'POST'])
@login_required
def show():
    avatar = session.get('avatar','')
    return render_template('frontend/show.html', active='show', avatar=avatar)

@frontend.route('/')
def index():
    if current_user.is_authenticated():
        return redirect(url_for('frontend.show'))
    monitors = ['rescuetime', 'fitbit', 'github', 'nike', 'argus', 'bong', 'ledongli', 'moves', 'uber', 'withings']
    return render_template('index.html', monitors=monitors)

@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('frontend.show'))
    next=request.args.get('next', None)
    redirect_uri = current_app.config.get('CALLBACK_URL') % 'github'
    oauth_url = 'https://github.com/login/oauth/authorize?redirect_uri=%s?next=%s&client_id=e925ef871d26e063315b' % (redirect_uri, next)
    return redirect(oauth_url)


@frontend.route('/<monitor_name>/callback', methods=['GET', 'POST'])
def callback(monitor_name):
    CALLBACK_URL = current_app.config.get('CALLBACK_URL')
    if monitor_name == 'github':
        code = request.args.get('code', None)
        next=request.args.get('next', None)
        params = {
                'client_id': current_app.config.get('GITHUB_KEY'),
                'redirect_uri': CALLBACK_URL % 'github',
                'client_secret': current_app.config.get('GITHUB_SECRET'),
                'code': code
            }
        url = 'https://github.com/login/oauth/access_token'
        req = requests.post(url=url, headers={'Accept': 'application/json'}, params=params)
        if req.status_code != 200:
            return redirect(url_for('frontend.login'))
        resp_json = json.loads(req.content)
        # get user token
        token = resp_json['access_token']
        req_url = 'https://api.github.com/user?access_token=%s' % token
        r = requests.get(req_url)
        user_json = json.loads(r.content)
        username = user_json['login']
        avatar_url = user_json['avatar_url']
        email = user_json['email'] if user_json['email'] else ''
        if not User.query.filter_by(name=username).first():
            print 'no user:%s' % username
            user = User(name=username, email=email, avatar=avatar_url)
            db.session.add(user)
            db.session.commit()
        user_one = User.query.filter_by(name=username).first()
        user_token = Tokens.query.filter_by(monitor_id=5, user_id=user_one.id, datatype='coding').first()
        if not user_token:
            user_token = Tokens(monitor_id=5, user_id=user_one.id, datatype='coding', token=token, name='github')
            db.session.add(user_token)
            db.session.commit()
            # 初始化爬取 github commit数据
            github_task_func.delay(token, username)
            print 'github task start....'
        login_user(user_one)
        session['avatar'] = user_one.avatar
        # if login_user(user_one):
        #     flash("Logged in", 'success')
        return redirect(next or url_for('frontend.show'))
    elif monitor_name == 'fitbit':
        if not current_user.is_authenticated():
            return redirect(url_for('frontend.login'))
        code = request.args.get('code', None)
        params = {
                'client_id': current_app.config.get('FITBIT_KEY'),
                'redirect_uri': CALLBACK_URL % 'fitbit',
                'grant_type': 'authorization_code',
                'code': code
            }
        base_str = 'Basic %s' % base64.b64encode('%s:%s' % (current_app.config.get('FITBIT_KEY'), current_app.config.get('FITBIT_SECRET')))
        headers = {
            'Authorization': base_str,
            'Content-Type': 'application/x-www-form-urlencoded'
        }
        url = 'https://api.fitbit.com/oauth2/token'
        req = requests.post(url=url, headers=headers, params=params)
        resp_json = json.loads(req.content)
        print resp_json
        token = resp_json['access_token']
        refresh_token = resp_json['refresh_token']
        print refresh_token
        user_token = Tokens.query.filter_by(monitor_id=3, user_id=current_user.id, datatype='health').first()
        if user_token:
            user_token.token = token
            user_token.refresh_token = refresh_token
            db.session.commit()
            flash(u'fitbit权限更新成功', 'success')
        else:
            user_token = Tokens(monitor_id=3, user_id=current_user.id, datatype='health', token=token, refresh_token=refresh_token, name='fitbit')
            db.session.add(user_token)
            db.session.commit()
            # 初始化爬取 fitbit 健康数据
            fitbit_task_func(token, current_user.name)
            print u'开始爬取fitbit数据'
            flash(u'fitbit权限认证成功', 'success')
        return redirect(url_for('monitor.list'))
    else:
        flash(u'未有此项目权限', 'success')
        return redirect(url_for('monitor.list'))



@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('avatar', None)
    # flash('Logged out', 'success')
    return redirect(url_for('frontend.index'))

@frontend.route('/about')
def about():
    return render_template('frontend/about.html', active='about')

baymax/monitor/__init__.py
from .views import monitor
from .models import Monitor, Tokens, MonitorValue
from .task import rescuetime_task, github_task, fitbit_task, github_task_func, fitbit_task_func, rescuetime_task_func

baymax/monitor/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, flash, redirect, url_for, session, current_app
from flask.ext.login import login_required, current_user
import urllib
from ..extensions import db
from ..libs.fitbit import Fitbit
from .models import Tokens, Monitor
from .task import rescuetime_task_func
from .forms import RescuetimeForm

monitor = Blueprint('monitor', __name__, url_prefix='/monitor')

@monitor.route('/', methods=['GET', 'POST'])
@login_required
def list():
    res = {'rescuetime':None, 'fitbit':None}
    avatar = session.get('avatar', None)
    user_tokens = Tokens.query.filter_by(user_id=current_user.id).all()
    for item in user_tokens:
        if item.name == 'rescuetime':
            res['rescuetime'] = True
        if item.name == 'fitbit':
            res['fitbit'] = True
    monitors = Monitor.query.filter(Monitor.name!='github').all()
    return render_template('monitor/list.html', res=res, active='monitor', avatar=avatar, monitors=monitors)


@monitor.route('/<monitor_name>', methods=['GET', 'POST'])
@login_required
def detail(monitor_name):
    redirect_uri = current_app.config.get('CALLBACK_URL') % 'github'
    if monitor_name == 'rescuetime':
        form = RescuetimeForm()
        if form.validate_on_submit():
            print form.key.data
            user_id = current_user.id
            web_tooken = Tokens.query.filter_by(monitor_id=2, user_id=user_id, datatype='webtimer').first()
            if web_tooken:
                web_tooken.token = form.key.data
                web_tooken.name = 'rescuetime'
                db.session.commit()
                flash(u'recuetime重新权限认证成功', 'success')
            else:
                token = Tokens(monitor_id=2, user_id=user_id, token=str(form.key.data), datatype='webtimer', name='rescuetime')
                db.session.add(token)
                db.session.commit()
                # 初始化爬取 rescuetime的数据
                rescuetime_task_func.delay(str(form.key.data), current_user.name)
                print u'rescuetime data'
                flash(u'recuetime权限认证成功', 'success')
            return redirect(url_for('monitor.list'))
        return render_template('monitor/detail.html', form=form, active='monitor')
    elif monitor_name == 'fitbit':
        authorize_url = Fitbit.get_auth_url()
        return redirect(authorize_url)
    else:
        flash(u'对不起，目前还未支持该检测项目或者您未将其点亮(赋予权限)', 'warning')
        return redirect(url_for('monitor.list'))
        # return render_template('monitor/detail.html', form=None, active='monitor')

baymax/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

baymax/user/views.py
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, render_template, send_from_directory, abort
from flask import current_app as APP
from flask.ext.login import login_required, current_user
from .models import User

user = Blueprint('user', __name__, url_prefix='/user')

@user.route('/')
@login_required
def index():
    if not current_user.is_authenticated():
        abort(403)
    return render_template('user/index.html', user=current_user)

baymax/templates/layouts/base.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{{ page_title|default('Project') }}{% endblock %} - Project</title>
    <meta name="description" content="baymax">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
    <style type="text/css">
        .grayscale { filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale");
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
            filter: gray;
            filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);
        }
        .header {
        background: linear-gradient(rgba(94,94,94,.5),rgba(94,94,94,.5)),url(/static/img/header.jpg) no-repeat center top;
        padding-top: 250px;
        background-attachment: relative;
        background-position: center center;
        background-size: 100%;
        background-size: cover;
        min-height: 700px;
        width: 100%;
        }
        .btn-demo {
            border-radius: 50px;
            margin-right: 15px;
            font-size: 11px;
            letter-spacing: 1px;
            text-transform: uppercase;
            padding: 14px 28px 13px 28px;
            background: 0 0;
            color: #fff;
            border: 2px solid #fff;
        }
        .btn-go {
            border-radius: 50px;
            margin-right: 15px;
            font-size: 20px;
            letter-spacing: 1px;
            padding: 14px 28px 13px 28px;
            color: #fff;
            border: 2px solid #555555;
            background: #6DB81C;
        }
        .btn-github{
            background: #6DB81C;
            color: #fff;
        }

    </style>
    {% endblock %}

</head>
<body style="padding-top: 20px; padding-bottom: 20px">

    {% block topbar %}
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">Baymax.ninja</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li>
                      <a href="https://github.com/no13bus/baymax" target="_blank"><i class="fa fa-github"></i> Source code</a>
                    </li>
                    <li {% if active and active == 'show' %}class="active"{% endif %}>
                      <a href="{{ url_for('frontend.show') }}"><i class="fa fa-bar-chart"></i> Show</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if not current_user.is_authenticated() %}
                      <li><a href="https://github.com/login/oauth/authorize?redirect_uri=http://baymax.ninja/github/callback&client_id=e925ef871d26e063315b" title="Sign in"><i class="fa fa-sign-in fa-lg"></i> Sign in</a></li>
                    {% else %}
                      <li>
                        <a href="{{ url_for('monitor.list') }}"><img src="{{ avatar }}" style="width: 20px; height:20px;" title="{{ current_user.name }}"/></a>
                      </li>
                      <li {% if active and active == 'monitor' %}class="active"{% endif %}>
                        <a href="{{ url_for('monitor.list') }}" title="Add a repo"><i class="fa fa-cog fa-lg"></i> Monitor</a>
                      </li>
                      <li>
                          <a href="{{ url_for('frontend.logout') }}" title="Sign out"><i class="fa fa-sign-out fa-lg"></i> Sign out</a>
                      </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block flash_message %}

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            <div class="container" style="padding-top: 50px;">
                <div class="container-fluid">
                    <div id='flash_message_container'>
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        {% endwith %}

    {% endblock %}



      {% block body %}
        <div class="container">
        </div>
      {% endblock %}


    {% block js_btm %}
    <script type="text/javascript" src="http://cdn.bootcss.com/jquery/2.1.4/jquery.js"></script>
    <script type="text/javascript" src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.js"></script>
    <script type="application/javascript" src="http://cdn.bootcss.com/highcharts/4.1.5/highcharts.js"></script>
    {% endblock %}

    {% block footer %}
    <div class="navbar-fixed-bottom" style="background: #2C3E50;font-size: 14px;text-align: center;color: #B4AFB4;padding-top: 22px;padding-bottom: 22px;">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <span>@<a href="https://github.com/no13bus" target="_blank">no13bus</a></span>
                    <span>Powered by <a href="https://github.com/mitsuhiko/flask" target="_blank">Flask</a></span> |
                    <span><a href="https://github.com/twbs/bootstrap" target="_blank">Bootstrap</a></span> |
                    <span><a href="http://www.linode.com/" target="_blank">Linode</a></span>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>